export const WebhookEventType = {
  ALERT_TRIGGERED: 'ALERT_TRIGGERED',
  INVENTORY_UPDATED: 'INVENTORY_UPDATED',
  NODE_TELEMETRY: 'NODE_TELEMETRY',
  TARGET_DETECTED: 'TARGET_DETECTED',
  NODE_ALERT: 'NODE_ALERT',
  DRONE_TELEMETRY: 'DRONE_TELEMETRY',
  COMMAND_ACK: 'COMMAND_ACK',
  COMMAND_RESULT: 'COMMAND_RESULT',
  SERIAL_RAW: 'SERIAL_RAW',
} as const;

export type WebhookEventType = (typeof WebhookEventType)[keyof typeof WebhookEventType];
